parameters:
  featurefactory:
    catalog: "hive_metastore"
    database: "odap_features_{entity}"
    features:
      latest_table: "latest"

    metadata:
      table: "metadata"
      
    #ids:
    #  table: "catalog.db.ids_table"

    entities:
      # 1. rename your entity e.g. client, customer, account, ...
      your_entity_name:
        # 2. change to id column which identifies your entity
        id_column: "your_id"
        id_column_type: "long"

  segmentfactory:
    catalog: "hive_metastore"
    database: "odap_segments"
    log:
      table: "export_log"

    segment:
      table: "segment_log"

    destinations:
      # 3. rename destination to export to
      your_destination:
        # 4. change to the name of your destination implementation .py file in the `export` folder
        type: "your_destination_type"

  usecasefactory:
    catalog: "hive_metastore"
    database: "odap_use_cases"
    table: "use_cases"
